version: "3.8"
services:
  api:
    image: city-api:1.0.2
    container_name: city-api
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: curl --silent --fail localhost:9200 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

